#ifndef PIANTOR_CONFIG_H
#define PIANTOR_CONFIG_H

#define ENABLE_COMPILE_KEYCODE

#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_TIME_TO_MAX 40
#define MOUSEKEY_DELAY 100
#define MOUSEKEY_WHEEL_DELAY 100
#define MOUSEKEY_WHEEL_INTERVAL 50
#define MOUSEKEY_WHEEL_TIME_TO_MAX 100

#define TAPPING_TERM 175
#define PERMISSIVE_HOLD
#define QUICK_TAP_TERM 0

#define COMBO_TERM 40
#define COMBO_MUST_HOLD_MODS
#define COMBO_HOLD_TERM 175

#endif /* PIANTOR_CONFIG_H */
